# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci
      run: npm ci --no-progress
    - name: Build
      run: npm run build:ci
    - name: ESLint
      uses: Krizzu/eslint-check-action@v1.1.0
      with:
        ghToken: ${{ secrets.GITHUB_TOKEN }}
        eslintFiles: "src"
        eslintConfig: ".eslintrc.json"
        eslintExt: "js, vue, ts, tsx"
    - name: Stylelint
      run: npm run lint:stylelint


